tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

ports:
- port: 8080
  onOpen: open-preview


vscode:
  extensions:
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
